name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger bei Push auf main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ GitHub Container Registry login
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}        # Dein Benutzername
          password: ${{ secrets.GITHUB_TOKEN }} # Automatisch verfügbar in Workflows

      # 3️⃣ Docker Image bauen
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/iso-updater:latest .

      # 4️⃣ Docker Image pushen
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/iso-updater:latest
